"""
Builds the final, polished .docx deliverable from the plan + executed
sections using python-docx.
"""

from __future__ import annotations

import datetime
import os
import re

from docx import Document
from docx.shared import Pt, Inches, RGBColor
from docx.enum.text import WD_ALIGN_PARAGRAPH
from docx.enum.table import WD_TABLE_ALIGNMENT
from docx.oxml.ns import qn

from .planner import PlanResult
from .executor import ExecutionResult

ACCENT_COLOR = RGBColor(0x1F, 0x3A, 0x5F)


def _set_cell_shading(cell, hex_color: str):
    tc_pr = cell._tc.get_or_add_tcPr()
    shd = tc_pr.makeelement(qn("w:shd"), {qn("w:val"): "clear", qn("w:color"): "auto", qn("w:fill"): hex_color})
    tc_pr.append(shd)


def build_docx(
    user_request: str,
    plan_result: PlanResult,
    execution_result: ExecutionResult,
    reflection_checks: list,
    reflection_confidence: float,
    summary: dict,
    output_dir: str,
    file_stem: str,
) -> str:
    doc = Document()

    # Base styling
    style = doc.styles["Normal"]
    style.font.name = "Calibri"
    style.font.size = Pt(11)

    # Title page block
    title_p = doc.add_paragraph()
    title_p.alignment = WD_ALIGN_PARAGRAPH.CENTER
    run = title_p.add_run(plan_result.title)
    run.bold = True
    run.font.size = Pt(26)
    run.font.color.rgb = ACCENT_COLOR

    subtitle_p = doc.add_paragraph()
    subtitle_p.alignment = WD_ALIGN_PARAGRAPH.CENTER
    sub_run = subtitle_p.add_run(plan_result.document_type.replace("_", " ").title())
    sub_run.italic = True
    sub_run.font.size = Pt(13)

    meta_p = doc.add_paragraph()
    meta_p.alignment = WD_ALIGN_PARAGRAPH.CENTER
    meta_run = meta_p.add_run(
        f"Generated by Autonomous Agent · {datetime.date.today().isoformat()} · "
        f"classification confidence {plan_result.classification_confidence:.0%} · "
        f"reflection confidence {reflection_confidence:.0%}"
    )
    meta_run.font.size = Pt(10)
    meta_run.font.color.rgb = RGBColor(0x66, 0x66, 0x66)

    doc.add_paragraph()  # spacer

    # Agent Decision Summary -- one-glance synthesis of the whole run
    doc.add_heading("Agent Decision Summary", level=2)
    summary_table = doc.add_table(rows=0, cols=2)
    summary_table.style = "Light Grid Accent 1"
    summary_rows = [
        ("Intent", summary.get("intent", "")),
        ("Detected type", summary.get("detected_type", "")),
        ("Classification confidence", f"{summary.get('classification_confidence', 0):.0%}"),
        ("Reflection confidence", f"{summary.get('reflection_confidence', 0):.0%}"),
        ("Assumptions made", str(summary.get("assumptions_count", 0))),
        ("Reflection issues found", str(summary.get("reflection_issues", 0))),
        ("Sections generated", str(summary.get("sections_generated", 0))),
        ("Sections regenerated/strengthened", str(summary.get("sections_regenerated", 0))),
        ("Execution time", f"{summary.get('execution_time_ms', 0)} ms"),
        ("Email requested", "Yes" if summary.get("email_requested") else "No"),
    ]
    if summary.get("email_requested"):
        # Placeholder rows -- the send happens AFTER this file is written
        # (email is only attempted once the document is safely persisted),
        # so these are patched in place by patch_email_status() once the
        # true outcome is known. A reader opening the file before that
        # patch runs would see "Pending", which is honest, not wrong.
        summary_rows.append(("Recipient", summary.get("email_recipient") or ""))
        summary_rows.append(("Delivery status", "Pending"))
        summary_rows.append(("Delivery time", "—"))
    for label, value in summary_rows:
        row = summary_table.add_row().cells
        row[0].text = label
        row[1].text = value

    doc.add_paragraph()

    # Original request block
    doc.add_heading("Original Request", level=2)
    req_p = doc.add_paragraph(user_request.strip())
    req_p.runs[0].italic = True

    # Classification reasoning -- makes the "why this document type"
    # decision visible in the deliverable itself, not just the API response.
    doc.add_heading("Classification Reasoning", level=2)
    doc.add_paragraph(plan_result.classification_reasoning)

    # Assumptions block (only if any -- this is what makes the "complex /
    # ambiguous" test case visibly different from the standard one)
    if plan_result.assumptions:
        doc.add_heading("Assumptions Made by the Agent", level=2)
        for a in plan_result.assumptions:
            doc.add_paragraph(a, style="List Bullet")

    doc.add_page_break()

    # Table of contents-ish section list is skipped for a 60-min build;
    # instead we go straight into the drafted sections.
    for section in execution_result.sections:
        doc.add_heading(section.title, level=1)
        for para in _split_paragraphs(section.content):
            if para.strip().startswith("- "):
                doc.add_paragraph(para.strip()[2:], style="List Bullet")
            else:
                doc.add_paragraph(para.strip())

    # Appendix: reflection / self-check results -- evaluate-then-repair,
    # so each row's status distinguishes "was fine" from "was fixed" from
    # "still unresolved," not just a pass/fail boolean.
    doc.add_page_break()
    doc.add_heading("Appendix A: Reflection & Self-Check", level=1)
    doc.add_paragraph(f"Post-repair reflection confidence: {reflection_confidence:.0%}")
    if reflection_checks:
        refl_table = doc.add_table(rows=1, cols=3)
        refl_table.style = "Light Grid Accent 1"
        refl_table.alignment = WD_TABLE_ALIGNMENT.CENTER
        hdr = refl_table.rows[0].cells
        hdr[0].text = "Expected element"
        hdr[1].text = "Status"
        hdr[2].text = "Note"
        for check in reflection_checks:
            row = refl_table.add_row().cells
            row[0].text = check.label
            row[1].text = check.status.upper()
            row[2].text = check.note
    else:
        doc.add_paragraph("No reflection checklist was defined for this document type.")

    # Appendix: execution log, for transparency into what the agent did.
    # Structured event model: each row is one action, not a loose sentence.
    doc.add_heading("Appendix B: Agent Execution Log", level=1)
    log_table = doc.add_table(rows=1, cols=5)
    log_table.style = "Light Grid Accent 1"
    log_table.alignment = WD_TABLE_ALIGNMENT.CENTER
    hdr = log_table.rows[0].cells
    hdr[0].text = "Timestamp"
    hdr[1].text = "Phase"
    hdr[2].text = "Action"
    hdr[3].text = "Duration"
    hdr[4].text = "Message"
    for entry in execution_result.log:
        row = log_table.add_row().cells
        row[0].text = entry.get("timestamp", "")
        row[1].text = entry.get("phase", "")
        row[2].text = entry.get("action", "")
        dur = entry.get("duration_ms")
        row[3].text = f"{dur} ms" if dur is not None else "—"
        row[4].text = entry.get("message", "")

    os.makedirs(output_dir, exist_ok=True)
    safe_stem = re.sub(r"[^a-zA-Z0-9_-]", "_", file_stem)[:60]
    file_name = f"{safe_stem}.docx"
    file_path = os.path.join(output_dir, file_name)
    doc.save(file_path)
    return file_path


def patch_execution_time(file_path: str, total_ms: int) -> None:
    """
    The Agent Decision Summary's execution time can't be known until AFTER
    the docx itself is assembled and saved (assembly time is part of the
    total). Rather than report an inaccurate pre-assembly estimate, this
    reopens the just-saved file and patches that one cell with the true
    total once main.py knows it. Small and slightly unusual, but it keeps
    the number in the document honest instead of silently wrong.
    """
    doc = Document(file_path)
    if not doc.tables:
        return
    summary_table = doc.tables[0]
    for row in summary_table.rows:
        if row.cells[0].text.strip() == "Execution time":
            row.cells[1].text = f"{total_ms} ms"
            break
    doc.save(file_path)


def patch_email_status(file_path: str, email: dict, duration_ms: int) -> None:
    """
    Companion to patch_execution_time(): email delivery is only attempted
    AFTER this file is written and persisted (see main.py's ordering), so
    the "Delivery status" / "Delivery time" rows are placeholders at write
    time. This reopens the saved file and fills in the real outcome once
    the send has actually been attempted.
    """
    doc = Document(file_path)
    if not doc.tables:
        return
    summary_table = doc.tables[0]
    for row in summary_table.rows:
        label = row.cells[0].text.strip()
        if label == "Delivery status":
            status_text = email.get("status", "unknown").upper()
            if email.get("status") == "failed" and email.get("error"):
                status_text += f" — {email['error'][:100]}"
            row.cells[1].text = status_text
        elif label == "Delivery time":
            row.cells[1].text = f"{duration_ms} ms"
    doc.save(file_path)


def _split_paragraphs(text: str) -> list[str]:
    parts = [p for p in re.split(r"\n+", text) if p.strip()]
    return parts if parts else [text]
